// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingCart.Infrastructure.Persistence;

#nullable disable

namespace ShoppingCart.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ShoppingCartDbContext))]
    partial class ShoppingCartDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShoppingCart.Domain.Entities.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<int?>("CouponId")
                        .HasColumnType("int")
                        .HasColumnName("CupomID");

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Desconto");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Status");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Subtotal");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Total");

                    b.HasKey("Id")
                        .HasName("PK_Carrinho");

                    b.HasIndex("CouponId");

                    b.ToTable("Carrinho", null, t =>
                        {
                            t.HasCheckConstraint("CK_Carrinho_Desconto_NaoNegativo", "[Desconto] >= 0");

                            t.HasCheckConstraint("CK_Carrinho_Subtotal_NaoNegativo", "[Subtotal] >= 0");

                            t.HasCheckConstraint("CK_Carrinho_Total_Valido", "[Total] >= 0 AND [Total] <= [Subtotal]");
                        });
                });

            modelBuilder.Entity("ShoppingCart.Domain.Entities.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CarrinhoID");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProdutoID");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Quantidade");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PrecoTotal");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PrecoUnitario");

                    b.HasKey("Id")
                        .HasName("PK_CarrinhoItem");

                    b.HasIndex("ProductId");

                    b.HasIndex("CartId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("UX_CarrinhoItem_Carrinho_Produto");

                    b.ToTable("CarrinhoItem", null, t =>
                        {
                            t.HasCheckConstraint("CK_CarrinhoItem_PrecoTotal_NaoNegativo", "[PrecoTotal] >= 0");

                            t.HasCheckConstraint("CK_CarrinhoItem_PrecoUnitario_NaoNegativo", "[PrecoUnitario] >= 0");

                            t.HasCheckConstraint("CK_CarrinhoItem_Quantidade_Positiva", "[Quantidade] > 0");
                        });
                });

            modelBuilder.Entity("ShoppingCart.Domain.Entities.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("CodigoCupom");

                    b.Property<decimal>("DiscountPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("PercentualDesconto");

                    b.HasKey("Id")
                        .HasName("PK_Cupom");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Cupom_CodigoCupom");

                    b.ToTable("Cupom", null, t =>
                        {
                            t.HasCheckConstraint("CK_Cupom_PercentualDesconto_Valido", "[PercentualDesconto] > 0 AND [PercentualDesconto] <= 100");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "10OFF",
                            DiscountPercentage = 10m
                        },
                        new
                        {
                            Id = 2,
                            Code = "15OFF",
                            DiscountPercentage = 15m
                        });
                });

            modelBuilder.Entity("ShoppingCart.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DescricaoProduto");

                    b.Property<decimal>("NetPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PrecoLiquido");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int")
                        .HasColumnName("QuantidadeEstoque");

                    b.HasKey("Id")
                        .HasName("PK_Produto");

                    b.ToTable("Produto", null, t =>
                        {
                            t.HasCheckConstraint("CK_Produto_PrecoLiquido_NaoNegativo", "[PrecoLiquido] >= 0");

                            t.HasCheckConstraint("CK_Produto_QuantidadeEstoque_NaoNegativa", "[QuantidadeEstoque] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Notebook Dell Inspiron 15",
                            NetPrice = 3499.90m,
                            StockQuantity = 8
                        },
                        new
                        {
                            Id = 2,
                            Description = "Mouse sem fio Logitech M170",
                            NetPrice = 59.90m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 3,
                            Description = "Teclado Mecânico Redragon Kumara",
                            NetPrice = 189.90m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 4,
                            Description = "Monitor LG 24' Full HD",
                            NetPrice = 749.00m,
                            StockQuantity = 12
                        },
                        new
                        {
                            Id = 5,
                            Description = "Headset Gamer HyperX Cloud Stinger",
                            NetPrice = 249.90m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 6,
                            Description = "Webcam Logitech C920",
                            NetPrice = 399.00m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 7,
                            Description = "SSD Kingston 480GB",
                            NetPrice = 219.90m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 8,
                            Description = "Cadeira Gamer ThunderX3",
                            NetPrice = 1099.00m,
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = 9,
                            Description = "Carregador USB-C 65W",
                            NetPrice = 89.90m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 10,
                            Description = "Hub USB 4 Portas 3.0",
                            NetPrice = 49.90m,
                            StockQuantity = 35
                        });
                });

            modelBuilder.Entity("ShoppingCart.Domain.Entities.Cart", b =>
                {
                    b.HasOne("ShoppingCart.Domain.Entities.Coupon", "AppliedCoupon")
                        .WithMany()
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Carrinho_Cupom");

                    b.Navigation("AppliedCoupon");
                });

            modelBuilder.Entity("ShoppingCart.Domain.Entities.CartItem", b =>
                {
                    b.HasOne("ShoppingCart.Domain.Entities.Cart", null)
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CarrinhoItem_Carrinho");

                    b.HasOne("ShoppingCart.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CarrinhoItem_Produto");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShoppingCart.Domain.Entities.Cart", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
